// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type Message struct {
	ID        int64
	RoomID    int64
	AuthorID  int64
	Body      string
	CreatedAt string
}

type Room struct {
	ID        int64
	Type      string
	Title     sql.NullString
	CreatedAt string
}

type RoomParticipant struct {
	RoomID   int64
	UserID   int64
	Role     sql.NullString
	JoinedAt string
}

type User struct {
	ID        int64
	Handle    string
	CreatedAt string
}
