// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const addParticipant = `-- name: AddParticipant :exec
INSERT INTO room_participants (room_id, user_id, role, joined_at)
VALUES (?, ?, ?, ?)
`

type AddParticipantParams struct {
	RoomID   int64
	UserID   int64
	Role     sql.NullString
	JoinedAt string
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) error {
	_, err := q.db.ExecContext(ctx, addParticipant,
		arg.RoomID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
	)
	return err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (type, title, created_at)
VALUES (?, ?, ?)
RETURNING id, type, title, created_at
`

type CreateRoomParams struct {
	Type      string
	Title     sql.NullString
	CreatedAt string
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom, arg.Type, arg.Title, arg.CreatedAt)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (handle, created_at)
VALUES (?, ?)
RETURNING id, handle, created_at
`

type CreateUserParams struct {
	Handle    string
	CreatedAt string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Handle, arg.CreatedAt)
	var i User
	err := row.Scan(&i.ID, &i.Handle, &i.CreatedAt)
	return i, err
}

const getRoom = `-- name: GetRoom :one
SELECT id, type, title, created_at FROM rooms WHERE id = ?
`

func (q *Queries) GetRoom(ctx context.Context, id int64) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByHandle = `-- name: GetUserByHandle :one
SELECT id, handle, created_at FROM users WHERE handle = ?
`

func (q *Queries) GetUserByHandle(ctx context.Context, handle string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByHandle, handle)
	var i User
	err := row.Scan(&i.ID, &i.Handle, &i.CreatedAt)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (room_id, author_id, body, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, room_id, author_id, body, created_at
`

type InsertMessageParams struct {
	RoomID    int64
	AuthorID  int64
	Body      string
	CreatedAt string
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, insertMessage,
		arg.RoomID,
		arg.AuthorID,
		arg.Body,
		arg.CreatedAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listMessagesByRoom = `-- name: ListMessagesByRoom :many
SELECT id, room_id, author_id, body, created_at
FROM messages
WHERE room_id = ?1
  AND (
      ?2 = ''
      OR created_at < ?2
      OR (created_at = ?2 AND id < ?3)
  )
ORDER BY created_at DESC, id DESC
LIMIT ?4
`

type ListMessagesByRoomParams struct {
	RoomID          int64
	CursorCreatedAt interface{}
	CursorID        int64
	PageLimit       int64
}

// ListMessagesByRoom returns one page of history, newest first.
// Keyset pagination over (created_at, id): pass the last row seen as the cursor
// to fetch the next (older) page. First page: cursor_created_at = ” (sentinel),
// which disables the bound. The cursor param names repeat, so sqlc collapses
// each to a single argument.
func (q *Queries) ListMessagesByRoom(ctx context.Context, arg ListMessagesByRoomParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByRoom,
		arg.RoomID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsForUser = `-- name: ListRoomsForUser :many
SELECT r.id, r.type, r.title, r.created_at
FROM rooms r
JOIN room_participants p ON p.room_id = r.id
WHERE p.user_id = ?
ORDER BY r.created_at DESC, r.id DESC
`

// ListRoomsForUser lists every room the user participates in, newest first.
func (q *Queries) ListRoomsForUser(ctx context.Context, userID int64) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listRoomsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roomParticipantExists = `-- name: RoomParticipantExists :one
SELECT EXISTS(
    SELECT 1 FROM room_participants WHERE room_id = ? AND user_id = ?
) AS present
`

type RoomParticipantExistsParams struct {
	RoomID int64
	UserID int64
}

func (q *Queries) RoomParticipantExists(ctx context.Context, arg RoomParticipantExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, roomParticipantExists, arg.RoomID, arg.UserID)
	var present bool
	err := row.Scan(&present)
	return present, err
}
